services:
  my-web:
    image: 925047940866.dkr.ecr.ap-southeast-1.amazonaws.com/std07/nginx2:latest
    pull_policy: if_not_present
    container_name: my-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      frontend-net:
          ipv4_address: 192.168.0.10
      shared-backend: # 공통 네트워크 이름 지정
    volumes:
      - shared-data:/var/log/nginx

networks:
  frontend-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
          ip_range: 192.168.0.0/24
          gateway: 192.168.0.1
  shared-backend:
    name: shared-backend-net # 도커가 이름을 마음대로 바꾸지 못하게 고정
    driver: bridge

volumes:
  shared-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/ec2-user/nginx/logs" # 🌟 경로를 ec2-user로 수정 완료